In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import sklearn.metrics as mc
from  sklearn.model_selection import train_test_split

In [2]:
pathName="H:\\dataPython\\caloriesData2\\exercise.csv"
pathName2="H:\\dataPython\\caloriesData2\\calories.csv"
data=pd.read_csv(pathName)
data2=pd.read_csv(pathName2)

In [3]:
data

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0      14733363    male   68   190.0    94.0      29.0       105.0       40.8
1      14861698  female   20   166.0    60.0      14.0        94.0       40.3
2      11179863    male   69   179.0    79.0       5.0        88.0       38.7
3      16180408  female   34   179.0    71.0      13.0       100.0       40.5
4      17771927  female   27   154.0    58.0      10.0        81.0       39.8
...         ...     ...  ...     ...     ...       ...         ...        ...
14995  15644082  female   20   193.0    86.0      11.0        92.0       40.4
14996  17212577  female   27   165.0    65.0       6.0        85.0       39.2
14997  17271188  female   43   159.0    58.0      16.0        90.0       40.1
14998  18643037    male   78   193.0    97.0       2.0        84.0       38.3
14999  11751526    male   63   173.0    79.0      18.0        92.0       40.5

[15000 rows x 8 columns]

In [4]:
data.columns

Index(['User_ID', 'Gender', 'Age', 'Height', 'Weight', 'Duration',
       'Heart_Rate', 'Body_Temp'],
      dtype='object')

In [5]:
data.values

array([[14733363, 'male', 68, ..., 29.0, 105.0, 40.8],
       [14861698, 'female', 20, ..., 14.0, 94.0, 40.3],
       [11179863, 'male', 69, ..., 5.0, 88.0, 38.7],
       ...,
       [17271188, 'female', 43, ..., 16.0, 90.0, 40.1],
       [18643037, 'male', 78, ..., 2.0, 84.0, 38.3],
       [11751526, 'male', 63, ..., 18.0, 92.0, 40.5]], dtype=object)

In [6]:
data.head()

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [7]:
data.tail()

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
14995  15644082  female   20   193.0    86.0      11.0        92.0       40.4
14996  17212577  female   27   165.0    65.0       6.0        85.0       39.2
14997  17271188  female   43   159.0    58.0      16.0        90.0       40.1
14998  18643037    male   78   193.0    97.0       2.0        84.0       38.3
14999  11751526    male   63   173.0    79.0      18.0        92.0       40.5

In [8]:
data.shape

(15000, 8)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   User_ID     15000 non-null  int64  
 1   Gender      15000 non-null  object 
 2   Age         15000 non-null  int64  
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
dtypes: float64(5), int64(2), object(1)
memory usage: 937.6+ KB


In [10]:
data.describe()

User_ID           Age        Height        Weight      Duration  \
count  1.500000e+04  15000.000000  15000.000000  15000.000000  15000.000000   
mean   1.497736e+07     42.789800    174.465133     74.966867     15.530600   
std    2.872851e+06     16.980264     14.258114     15.035657      8.319203   
min    1.000116e+07     20.000000    123.000000     36.000000      1.000000   
25%    1.247419e+07     28.000000    164.000000     63.000000      8.000000   
50%    1.499728e+07     39.000000    175.000000     74.000000     16.000000   
75%    1.744928e+07     56.000000    185.000000     87.000000     23.000000   
max    1.999965e+07     79.000000    222.000000    132.000000     30.000000   

         Heart_Rate     Body_Temp  
count  15000.000000  15000.000000  
mean      95.518533     40.025453  
std        9.583328      0.779230  
min       67.000000     37.100000  
25%       88.000000     39.600000  
50%       96.000000     40.200000  
75%      103.000000     40.600000  
max      128.000000     41.500000

In [11]:
data2

User_ID  Calories
0      14733363     231.0
1      14861698      66.0
2      11179863      26.0
3      16180408      71.0
4      17771927      35.0
...         ...       ...
14995  15644082      45.0
14996  17212577      23.0
14997  17271188      75.0
14998  18643037      11.0
14999  11751526      98.0

[15000 rows x 2 columns]

In [12]:
data2.head()

User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [13]:
data2.tail()

User_ID  Calories
14995  15644082      45.0
14996  17212577      23.0
14997  17271188      75.0
14998  18643037      11.0
14999  11751526      98.0

In [14]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   User_ID   15000 non-null  int64  
 1   Calories  15000 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 234.5 KB


In [15]:
data2.describe()

User_ID      Calories
count  1.500000e+04  15000.000000
mean   1.497736e+07     89.539533
std    2.872851e+06     62.456978
min    1.000116e+07      1.000000
25%    1.247419e+07     35.000000
50%    1.499728e+07     79.000000
75%    1.744928e+07    138.000000
max    1.999965e+07    314.000000

In [16]:
data2.values

array([[1.4733363e+07, 2.3100000e+02],
       [1.4861698e+07, 6.6000000e+01],
       [1.1179863e+07, 2.6000000e+01],
       ...,
       [1.7271188e+07, 7.5000000e+01],
       [1.8643037e+07, 1.1000000e+01],
       [1.1751526e+07, 9.8000000e+01]])

In [17]:
data["Gender"]=data["Gender"].map({"female":1,"male":0})

In [18]:
data

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0      14733363       0   68   190.0    94.0      29.0       105.0       40.8
1      14861698       1   20   166.0    60.0      14.0        94.0       40.3
2      11179863       0   69   179.0    79.0       5.0        88.0       38.7
3      16180408       1   34   179.0    71.0      13.0       100.0       40.5
4      17771927       1   27   154.0    58.0      10.0        81.0       39.8
...         ...     ...  ...     ...     ...       ...         ...        ...
14995  15644082       1   20   193.0    86.0      11.0        92.0       40.4
14996  17212577       1   27   165.0    65.0       6.0        85.0       39.2
14997  17271188       1   43   159.0    58.0      16.0        90.0       40.1
14998  18643037       0   78   193.0    97.0       2.0        84.0       38.3
14999  11751526       0   63   173.0    79.0      18.0        92.0       40.5

[15000 rows x 8 columns]

In [19]:
x=data.iloc[:,:].values

In [20]:
x

array([[1.4733363e+07, 0.0000000e+00, 6.8000000e+01, ..., 2.9000000e+01,
        1.0500000e+02, 4.0800000e+01],
       [1.4861698e+07, 1.0000000e+00, 2.0000000e+01, ..., 1.4000000e+01,
        9.4000000e+01, 4.0300000e+01],
       [1.1179863e+07, 0.0000000e+00, 6.9000000e+01, ..., 5.0000000e+00,
        8.8000000e+01, 3.8700000e+01],
       ...,
       [1.7271188e+07, 1.0000000e+00, 4.3000000e+01, ..., 1.6000000e+01,
        9.0000000e+01, 4.0100000e+01],
       [1.8643037e+07, 0.0000000e+00, 7.8000000e+01, ..., 2.0000000e+00,
        8.4000000e+01, 3.8300000e+01],
       [1.1751526e+07, 0.0000000e+00, 6.3000000e+01, ..., 1.8000000e+01,
        9.2000000e+01, 4.0500000e+01]])

In [22]:
y=data2["Calories"].values

In [23]:
y

array([231.,  66.,  26., ...,  75.,  11.,  98.])

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=(0))

In [32]:
x_train

array([[1.3693592e+07, 0.0000000e+00, 6.2000000e+01, ..., 4.0000000e+00,
        8.3000000e+01, 3.8900000e+01],
       [1.7907212e+07, 0.0000000e+00, 2.3000000e+01, ..., 1.2000000e+01,
        9.8000000e+01, 4.0300000e+01],
       [1.2132339e+07, 0.0000000e+00, 6.0000000e+01, ..., 2.1000000e+01,
        9.7000000e+01, 4.0400000e+01],
       ...,
       [1.7499944e+07, 1.0000000e+00, 3.6000000e+01, ..., 2.2000000e+01,
        1.0600000e+02, 4.0600000e+01],
       [1.1857300e+07, 1.0000000e+00, 5.6000000e+01, ..., 1.3000000e+01,
        9.4000000e+01, 3.9900000e+01],
       [1.4946022e+07, 0.0000000e+00, 2.8000000e+01, ..., 2.0000000e+00,
        7.2000000e+01, 3.8000000e+01]])

In [33]:
y_train

array([ 17.,  55., 134., ..., 137.,  69.,   1.])

In [34]:
x_test

array([[1.6303342e+07, 1.0000000e+00, 2.7000000e+01, ..., 9.0000000e+00,
        9.4000000e+01, 3.9800000e+01],
       [1.7054684e+07, 0.0000000e+00, 2.8000000e+01, ..., 6.0000000e+00,
        8.2000000e+01, 3.9300000e+01],
       [1.5568358e+07, 1.0000000e+00, 2.8000000e+01, ..., 2.2000000e+01,
        9.5000000e+01, 4.0800000e+01],
       ...,
       [1.7913021e+07, 1.0000000e+00, 2.3000000e+01, ..., 1.7000000e+01,
        1.0000000e+02, 4.0400000e+01],
       [1.1763584e+07, 0.0000000e+00, 2.3000000e+01, ..., 2.7000000e+01,
        1.0900000e+02, 4.0700000e+01],
       [1.3485137e+07, 1.0000000e+00, 2.3000000e+01, ..., 5.0000000e+00,
        9.4000000e+01, 3.9400000e+01]])

In [35]:
y_test

array([ 43.,  15., 101., ...,  87., 170.,  24.])

In [28]:
LR=LinearRegression()

In [29]:
LR.fit(x_train,y_train)

LinearRegression()

In [30]:
y_predict=LR.predict(x)

In [31]:
y_predict

array([199.64785292,  57.93493354,  39.81699004, ...,  78.90339079,
        26.62110994, 101.54582483])

In [36]:
print("Errors Values = ",mc.mean_absolute_error(y, y_predict))

Errors Values =  8.365376099451051


In [37]:
import seaborn as sns